-- Email verification code flow for login ID lookup and password reset.
-- Safe to run more than once: existing objects are ignored.

BEGIN
    EXECUTE IMMEDIATE '
        CREATE SEQUENCE SEQ_EMAIL_VERIFICATION_CODES
        START WITH 1
        INCREMENT BY 1
        NOCACHE
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE EMAIL_VERIFICATION_CODES (
            VERIFICATION_ID NUMBER(19) PRIMARY KEY,
            PURPOSE VARCHAR2(30) NOT NULL,
            USER_ID NUMBER(19) NOT NULL,
            LOGIN_ID VARCHAR2(50),
            EMAIL VARCHAR2(100) NOT NULL,
            CODE_HASH VARCHAR2(255) NOT NULL,
            EXPIRES_AT TIMESTAMP NOT NULL,
            VERIFIED_AT TIMESTAMP,
            CONSUMED_AT TIMESTAMP,
            ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
            CREATED_AT TIMESTAMP NOT NULL,
            CONSTRAINT FK_EMAIL_VERIFICATION_USER
                FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX IDX_EMAIL_VERIFICATION_USER_PURPOSE
        ON EMAIL_VERIFICATION_CODES (USER_ID, PURPOSE, CONSUMED_AT)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE SEQUENCE SEQ_PASSWORD_RESET_TOKENS
        START WITH 1
        INCREMENT BY 1
        NOCACHE
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE PASSWORD_RESET_TOKENS (
            RESET_TOKEN_ID NUMBER(19) PRIMARY KEY,
            USER_ID NUMBER(19) NOT NULL,
            TOKEN_HASH VARCHAR2(255) NOT NULL,
            EXPIRES_AT TIMESTAMP NOT NULL,
            USED_AT TIMESTAMP,
            CREATED_AT TIMESTAMP NOT NULL,
            CONSTRAINT FK_PASSWORD_RESET_TOKEN_USER
                FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX IDX_PASSWORD_RESET_TOKEN_USER
        ON PASSWORD_RESET_TOKENS (USER_ID, USED_AT)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
