ALTER SESSION DISABLE PARALLEL DML;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_USERS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_ROLES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_ROLES START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_PERMISSIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PERMISSIONS START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_USER_ROLES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_USER_ROLES START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_ROLE_PERMISSIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_ROLE_PERMISSIONS START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

MERGE INTO ROLES r
USING (
    SELECT 'ADMIN' ROLE_CODE, 'Administrator' ROLE_NAME, 'SYSTEM' ROLE_GROUP, 'Full system management role' DESCRIPTION, 1 SORT_ORDER FROM DUAL
    UNION ALL SELECT 'REQUESTER', 'Requester', 'BUSINESS', 'Can create and view purchase requests', 2 FROM DUAL
    UNION ALL SELECT 'APPROVER', 'Approver', 'BUSINESS', 'Can approve or reject purchase requests', 3 FROM DUAL
) src
ON (r.ROLE_CODE = src.ROLE_CODE)
WHEN NOT MATCHED THEN
    INSERT (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_GROUP, DESCRIPTION, SORT_ORDER, USE_YN, CREATED_AT, UPDATED_AT)
    VALUES (SEQ_ROLES.NEXTVAL, src.ROLE_CODE, src.ROLE_NAME, src.ROLE_GROUP, src.DESCRIPTION, src.SORT_ORDER, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;

MERGE INTO PERMISSIONS p
USING (
    SELECT 'USER_MANAGE' PERMISSION_CODE, 'Manage users' PERMISSION_NAME, 'SYSTEM' PERMISSION_GROUP, 'View users, approve users, and assign roles' DESCRIPTION FROM DUAL
    UNION ALL SELECT 'ROLE_MANAGE', 'Manage roles', 'SYSTEM', 'Manage roles and permissions' FROM DUAL
    UNION ALL SELECT 'PRODUCT_READ', 'Read products', 'PRODUCT', 'View product list and detail' FROM DUAL
    UNION ALL SELECT 'PRODUCT_WRITE', 'Write products', 'PRODUCT', 'Create and update products' FROM DUAL
    UNION ALL SELECT 'SUPPLIER_READ', 'Read suppliers', 'SUPPLIER', 'View supplier list and detail' FROM DUAL
    UNION ALL SELECT 'SUPPLIER_MANAGE', 'Manage suppliers', 'SUPPLIER', 'Create, update, and deactivate suppliers' FROM DUAL
    UNION ALL SELECT 'PURCHASE_REQUEST_CREATE', 'Create purchase requests', 'PURCHASE', 'Create purchase requests' FROM DUAL
    UNION ALL SELECT 'PURCHASE_REQUEST_APPROVE', 'Approve purchase requests', 'PURCHASE', 'Approve or reject purchase requests' FROM DUAL
) src
ON (p.PERMISSION_CODE = src.PERMISSION_CODE)
WHEN NOT MATCHED THEN
    INSERT (PERMISSION_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_GROUP, DESCRIPTION, USE_YN, CREATED_AT, UPDATED_AT)
    VALUES (SEQ_PERMISSIONS.NEXTVAL, src.PERMISSION_CODE, src.PERMISSION_NAME, src.PERMISSION_GROUP, src.DESCRIPTION, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;

MERGE INTO USERS u
USING (
    SELECT 'admin' LOGIN_ID,
           '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy' PASSWORD,
           'Administrator' USER_NAME,
           'admin@buyflow.local' EMAIL
    FROM DUAL
) src
ON (u.LOGIN_ID = src.LOGIN_ID)
WHEN NOT MATCHED THEN
    INSERT (USER_ID, LOGIN_ID, PASSWORD, USER_NAME, EMAIL, STATUS, USE_YN, CREATED_AT, UPDATED_AT)
    VALUES (SEQ_USERS.NEXTVAL, src.LOGIN_ID, src.PASSWORD, src.USER_NAME, src.EMAIL, 'ACTIVE', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;

MERGE INTO USER_ROLES ur
USING (
    SELECT u.USER_ID, r.ROLE_ID
    FROM USERS u
    JOIN ROLES r ON r.ROLE_CODE = 'ADMIN'
    WHERE u.LOGIN_ID = 'admin'
) src
ON (ur.USER_ID = src.USER_ID AND ur.ROLE_ID = src.ROLE_ID)
WHEN NOT MATCHED THEN
    INSERT (USER_ROLE_ID, USER_ID, ROLE_ID, CREATED_AT)
    VALUES (SEQ_USER_ROLES.NEXTVAL, src.USER_ID, src.ROLE_ID, SYSTIMESTAMP);

COMMIT;

MERGE INTO ROLE_PERMISSIONS rp
USING (
    SELECT r.ROLE_ID, p.PERMISSION_ID
    FROM ROLES r
    CROSS JOIN PERMISSIONS p
    WHERE r.ROLE_CODE = 'ADMIN'
) src
ON (rp.ROLE_ID = src.ROLE_ID AND rp.PERMISSION_ID = src.PERMISSION_ID)
WHEN NOT MATCHED THEN
    INSERT (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, CREATED_AT)
    VALUES (SEQ_ROLE_PERMISSIONS.NEXTVAL, src.ROLE_ID, src.PERMISSION_ID, SYSTIMESTAMP);

COMMIT;

MERGE INTO ROLE_PERMISSIONS rp
USING (
    SELECT r.ROLE_ID, p.PERMISSION_ID
    FROM ROLES r
    JOIN PERMISSIONS p ON p.PERMISSION_CODE IN ('PURCHASE_REQUEST_CREATE')
    WHERE r.ROLE_CODE = 'REQUESTER'
) src
ON (rp.ROLE_ID = src.ROLE_ID AND rp.PERMISSION_ID = src.PERMISSION_ID)
WHEN NOT MATCHED THEN
    INSERT (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, CREATED_AT)
    VALUES (SEQ_ROLE_PERMISSIONS.NEXTVAL, src.ROLE_ID, src.PERMISSION_ID, SYSTIMESTAMP);

COMMIT;

MERGE INTO ROLE_PERMISSIONS rp
USING (
    SELECT r.ROLE_ID, p.PERMISSION_ID
    FROM ROLES r
    JOIN PERMISSIONS p ON p.PERMISSION_CODE IN ('PURCHASE_REQUEST_APPROVE')
    WHERE r.ROLE_CODE = 'APPROVER'
) src
ON (rp.ROLE_ID = src.ROLE_ID AND rp.PERMISSION_ID = src.PERMISSION_ID)
WHEN NOT MATCHED THEN
    INSERT (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, CREATED_AT)
    VALUES (SEQ_ROLE_PERMISSIONS.NEXTVAL, src.ROLE_ID, src.PERMISSION_ID, SYSTIMESTAMP);

COMMIT;
