DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'USERS'
       AND COLUMN_NAME = 'DEPARTMENT_NAME';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (DEPARTMENT_NAME VARCHAR2(100))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'USERS'
       AND COLUMN_NAME = 'POSITION_NAME';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (POSITION_NAME VARCHAR2(50))';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'USERS'
       AND COLUMN_NAME = 'JOB_RANK';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[ALTER TABLE USERS ADD (JOB_RANK VARCHAR2(20) DEFAULT 'USER')]';
    END IF;
END;
/

UPDATE USERS
   SET JOB_RANK = 'USER'
 WHERE JOB_RANK IS NULL;

UPDATE USERS u
   SET JOB_RANK = 'ADMIN'
 WHERE EXISTS (
       SELECT 1
         FROM USER_ROLES ur
         JOIN ROLES r ON r.ROLE_ID = ur.ROLE_ID
        WHERE ur.USER_ID = u.USER_ID
          AND r.ROLE_CODE = 'ADMIN'
 );

COMMIT;
